import ply.yacc as yacc
from lexico import tokens
from main import entradaJson
import warnings
warnings.filterwarnings("ignore")

def p_sigma(p):
    '''sigma : EMPRESAS'''
    print("El documento JSON es correcto")

def p_empresas(p):
    '''EMPRESASN : LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA VERSION LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA VERSION COMA FIRMA_DIGITAL LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA FIRMA_DIGITAL LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA FIRMA_DIGITAL COMA VERSION LLAVEC
    '''

def p_empresa(p):
    '''EMPRESA : LLAVEA NOMBRE_EMPRESA FUNDACION DIRECCION INGRESOS_ANUALES PYME LINK DEPARTAMENTOS LLAVEC COMA
        | LLAVEA NOMBRE_EMPRESA FUNDACION INGRESOS_ANUALES PYME LINK DEPARTAMENTOS LLAVEC COMA
        | LLAVEA NOMBRE_EMPRESA FUNDACION DIRECCION INGRESOS_ANUALES PYME DEPARTAMENTOS LLAVEC COMA
        | LLAVEA NOMBRE_EMPRESA FUNDACION INGRESOS_ANUALES PYME DEPARTAMENTOS LLAVEC COMA
        | LLAVEA NOMBRE_EMPRESA FUNDACION DIRECCION INGRESOS_ANUALES PYME LINK DEPARTAMENTOS LLAVEC COMA EMPRESA
        | LLAVEA NOMBRE_EMPRESA FUNDACION INGRESOS_ANUALES PYME LINK DEPARTAMENTOS LLAVEC COMA EMPRESA
        | LLAVEA NOMBRE_EMPRESA FUNDACION DIRECCION INGRESOS_ANUALES PYME DEPARTAMENTOS LLAVEC COMA EMPRESA
        | LLAVEA NOMBRE_EMPRESA FUNDACION INGRESOS_ANUALES PYME DEPARTAMENTOS LLAVEC COMA EMPRESA
    '''

def p_nombre_empresa(p):
    '''NOMBRE_EMPRESA DPUNTOS STRING COMA'''

def p_fundacion(p):
    '''FUNDACION DPUNTOS INTEGER COMA'''

def p_ingresos_anuales(p):
    '''INGRESOS_ANUALES DPUNTOS FLOAT COMA'''

def p_pyme(p):
    '''PYME DPUNTOS BOOLEAN COMA'''

def p_link(P):
    '''LINK DPUNTOS URI COMA | LINK DPUNTOS NULL COMA'''

def p_direccion(p):
    '''DIRECCION DPUNTOS LLAVEA CALLE CIUDAD PAIS LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA CALLE COMA PAIS COMA CIUDAD LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA CIUDAD COMA CALLE COMA PAIS LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA CIUDAD COMA PAIS COMA CALLE LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA PAIS COMA CALLE COMA CIUDAD LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA PAIS COMA CIUDAD COMA CALLE LLAVEC COMA
        | DIRECCION DPUNTOS LLAVEA LLAVEC
        | DIRECCION DPUNTOS NULL COMA
    '''

def p_calle(P):
    '''CALLE DPUNTOS STRING'''

def p_ciudad(P):
    '''CIUDAD DPUNTOS STRING'''

def p_pais(P):
    '''PAIS DPUNTOS STRING'''

def p_departamentos(P):
    '''DEPARTAMENTO DPUNTOS CORCHETEA DEPARTAMENTO CORCHETEC
    '''

def p_departamento(p):
    '''LLAVEA NOMBRE COMA JEFE COMA SUBDEPARTAMENTOS LLAVEC
        | LLAVEA NOMBRE COMA SUBDEPARTAMENTOS COMA JEFE LLAVEC
        | LLAVEA JEFE COMA NOMBRE COMA SUBDEPARTAMENTOS LLAVEC
        | LLAVEA JEFE COMA SUBDEPARTAMENTOS COMA NOMBRE LLAVEC
        | LLAVEA SUBDEPARTAMENTOS COMA NOMBRE COMA JEFE LLAVEC
        | LLAVEA SUBDEPARTAMENTOS COMA JEFE COMA NOMBRE LLAVEC
        | LLAVEA NOMBRE COMA SUBDEPARTAMENTOS LLAVEC
        | LLAVEA SUBDEPARTAMENTOS COMA NOMBRE LLAVEC
        | LLAVEA NOMBRE COMA JEFE COMA SUBDEPARTAMENTOS LLAVEC COMA DEPARTAMENTOS
        | LLAVEA NOMBRE COMA SUBDEPARTAMENTOS COMA JEFE LLAVEC COMA DEPARTAMENTOS
        | LLAVEA JEFE COMA NOMBRE COMA SUBDEPARTAMENTOS LLAVEC COMA DEPARTAMENTOS
        | LLAVEA JEFE COMA SUBDEPARTAMENTOS COMA NOMBRE LLAVEC COMA DEPARTAMENTOS
        | LLAVEA SUBDEPARTAMENTOS COMA NOMBRE COMA JEFE LLAVEC COMA DEPARTAMENTOS
        | LLAVEA SUBDEPARTAMENTOS COMA JEFE COMA NOMBRE LLAVEC COMA DEPARTAMENTOS
        | LLAVEA NOMBRE COMA SUBDEPARTAMENTOS LLAVEC COMA DEPARTAMENTOS
        | LLAVEA SUBDEPARTAMENTOS COMA NOMBRE LLAVEC COMA DEPARTAMENTOS
    '''

def p_nombre(p):
    '''NOMBRE DPUNTOS STRING'''

def p_jefe(p):
    '''JEFE DPUNTOS STRING | JEFE DPUNTOS NULL'''

def p_subdepartamentos(p):
    '''SUBDEPARTAMENTOS DPUNTOS CORCHETEA SUBDEPARTAMENTO CORCHETEC COMA
    '''

def p_subdepartamento(p):
    '''CORCHETEA NOMBRE COMA JEFE COMA EMPLEADOS CORCHETEC
        | CORCHETEA NOMBRE COMA EMPLEADOS COMA JEFE CORCHETEC
        | CORCHETEA JEFE COMA EMPLEADOS COMA NOMBRE CORCHETEC
        | CORCHETEA JEFE COMA NOMBRE COMA EMPLEADOS CORCHETEC
        | CORCHETEA EMPLEADOS COMA NOMBRE COMA JEFE CORCHETEC
        | CORCHETEA EMPLEADOS COMA JEFE COMA NOMBRE CORCHETEC
        | CORCHETEA NOMBRE COMA EMPLEADOS CORCHETEC
        | CORCHETEA NOMBRE COMA JEFE CORCHETEC
        | CORCHETEA NOMBRE CORCHETEC
        | CORCHETEA EMPLEADOS COMA NOMBRE CORCHETEC
        | CORCHETEA JEFE COMA NOMBRE CORCHETEC
        | CORCHETEA NOMBRE COMA JEFE COMA EMPLEADOS CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA NOMBRE COMA EMPLEADOS COMA JEFE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA JEFE COMA EMPLEADOS COMA NOMBRE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA JEFE COMA NOMBRE COMA EMPLEADOS CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA EMPLEADOS COMA NOMBRE COMA JEFE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA EMPLEADOS COMA JEFE COMA NOMBRE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA NOMBRE COMA EMPLEADOS CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA NOMBRE COMA JEFE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA NOMBRE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA EMPLEADOS COMA NOMBRE CORCHETEC COMA SUBDEPARTAMENTOS
        | CORCHETEA JEFE COMA NOMBRE CORCHETEC COMA SUBDEPARTAMENTOS
    '''

def p_empleados(p):
    '''EMPLEADOS DPUNTOS CORCHETEA EMPLEADO CORCHETEC
        | EMPLEADOS DPUNTOS CORCHETEA CORCHETEC
        | EMPLEADOS DPUNTOS NULL
    '''

def p_empleado(p):
    '''LLAVEA NOMBRE COMA EDAD COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION COMA PROYECTOS LLAVEC
        | LLAVEA NOMBRE COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION COMA PROYECTOS LLAVEC
        | LLAVEA NOMBRE COMA EDAD COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION LLAVEC
        | LLAVEA NOMBRE COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION LLAVEC
        | LLAVEA NOMBRE COMA EDAD COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION COMA PROYECTOS LLAVEC COMA EMPLEADOS
        | LLAVEA NOMBRE COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION COMA PROYECTOS LLAVEC COMA EMPLEADOS
        | LLAVEA NOMBRE COMA EDAD COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION LLAVEC COMA EMPLEADOS
        | LLAVEA NOMBRE COMA CARGO COMA SALARIO COMA ACTIVO COMA FECHA_CONTRATACION LLAVEC COMA EMPLEADOS
    '''

def p_edad(p):
    '''EDAD DPUNTOS INTEGER | EDAD DPUNTOS NULL
    '''

def p_cargo(p):
    '''CARGO DPUNTOS CARGOS
    '''

def p_salario(p):
    '''SALARIO DPUNTOS FLOAT
    '''

def p_activo(p):
    '''ACTIVO DPUNTOS BOOLEAN
    '''

def p_fecha_contratacion(p):
    '''FECHA_CONTRATACION DPUNTOS FECHA'''

def p_proyectos(p):
    '''PROYECTOS DPUNTOS CORCHETEA PROYECTO CORCHETEC
        | PROYECTOS DPUNTOS CORCHETEA CORCHETEC
        | PROYECTOS DPUNTOS NULL
    '''

def p_proyecto(p):
    '''LLAVEA NOMBRE COMA ESTADO COMA FECA_INICIO COMA FECHA_FIN LLAVEC
        | LLAVEA NOMBRE COMA FECA_INICIO COMA FECHA_FIN LLAVEC
        | LLAVEA NOMBRE COMA ESTADO COMA FECA_INICIO LLAVEC
        | LLAVEA NOMBRE COMA FECA_INICIO LLAVEC
        | LLAVEA NOMBRE COMA ESTADO COMA FECA_INICIO COMA FECHA_FIN LLAVEC COMA PROYECTOS
        | LLAVEA NOMBRE COMA FECA_INICIO COMA FECHA_FIN LLAVEC COMA PROYECTOS
        | LLAVEA NOMBRE COMA ESTADO COMA FECA_INICIO LLAVEC COMA PROYECTOS
        | LLAVEA NOMBRE COMA FECA_INICIO LLAVEC COMA PROYECTOS
    '''

def p_estados(p):
    '''ESTADO DPUNTOS ESTADOS | ESTADOS DPUNTOS NULL
    '''

def p_fecha_inicio(p):
    '''FECHA_INICIO DPUNTOS FECHA
    '''

def p_fecha_fin(p):
    '''FECHA_FIN DPUNTOS FECHA | FECHA_FIN DPUNTOS NULL
    '''

def p_error(p):
    print("Error sintáctico en '%s'" % p.value + " [Línea: %d]" % p.lineno)

parser = yacc.yacc(debug=0,start='sigma')
result = parser.parse(entradaJson)