import ply.yacc as yacc
from lexico import tokens
import warnings
warnings.filterwarnings("ignore")

def p_sigma(p):
    '''sigma : EMPRESAS'''
    print("El documento JSON es correcto")

def p_empresas(p):
    '''EMPRESASN : LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA VERSION LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA VERSION COMA FIRMA_DIGITAL LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA FIRMA_DIGITAL LLAVEC
        | LLAVEA EMPRESAS DPUNTOS CORCHETEA EMPRESA CORCHETEC COMA FIRMA_DIGITAL COMA VERSION LLAVEC
    '''